---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: go-store
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/go
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: stack
spec:
  id: io.buildpacks.stacks.bionic
  buildImage:
    image: paketobuildpacks/build:base-cnb
  runImage:
    image: paketobuildpacks/run:base-cnb
---
apiVersion: kpack.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: go-builder
spec:
  serviceAccountRef:
    name: service-account
    namespace: dev
  tag:  chanwit/demo-go-builder
  stack:
    name: stack
    kind: ClusterStack
  store:
    name: go-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/go
