apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
spec:
  encryptedData:
    .dockerconfigjson: AgCAs/XY4BVT0pKA7GWYDS8wKHq64PGyMdZF0nm3+WB5tNFNbswD8OUNW+xdNxJOWEyYhXORCHlNZgKcC0dy2HByl2kdQG0zty7XhYFOJywdz5Dg7CCk+AEdbGE0EUN8vnj3d1SuWQvHY2JLdv8f5RO93LpK0+Ze0NKNTTdO265WTkDHLiQ9Dl/45jwjr6Rv+Yte2CIWZ+fItCBDRzvJfvtf4UWRSt/L18QiAoqEugyNBPAXiBmLNI04V9d+UkEVEhNrqN4iIyZCboYppWSLVXAYDYNRnwKtZnFRwP/qYdlFbUVtzftc4wEtNZfSnaIknQisI1OaIcEOIdJ17BPHxMSAURF47WNApYW1GzrOrhVCf2ZIKor2XSM2ButCC/pdCNC2pnZwbv4r8wh0hTEshMYPK3uG/KSNB/n8weH2x0C6eWT/uwyHuBRvvpxv4G0SCwFnRr3+Jgw4akulCGG8WeKsAc+4PqXTqtb+4nf8bQ++Af0MwjSOGvNDDkxVnHXybhj0xhQI23FZbNP/g+X0DYBSRCcG0IPKJnKxGYnaoZGeZFYHbz02x0pKoP4ho5VzeLGMg+X+or+qI26GIUaysath35ByLNVzEJsGNwflzT+xw7n3QL8/Pc9dLIgkk/IOuzVu8uvhrLb90Rm3Z3murZJo5iuPRxh69EU1/qdm1XMncUnbCXNTsJXtgNoor/dhseQDhBF9l5ZUDuoShf7uhQ2hmxD5QnzTC8ABqwOH270oHcwTw4c297omGmq26KgZWvrK6bQODsDVRytyxE8Ye0Fb6En+f1rvTHMIU/ESNTvCAYVZNCwqsXLhRzucpUjfM0ZzgG5Ryb5kcqwtf+Quaf5/cW57yAMFAlNY2P2YDMsiD2+eSti5zXzO3VTOJBrDP8II570JbCX/f/UffGpAbkeRI0kx
  template:
    metadata:
      name: registry-credentials
    type: kubernetes.io/dockerconfigjson
