---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 10p-25-tekton
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_artifacts/10-platform-ops/10p-25-tekton
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: tekton-pipelines-controller
    namespace: tekton-pipelines
