---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 010-kpack-builder
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_commons/020-app-ops/010-kpack-builder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: dev
  dependsOn:
  - name: 020-kpack
