---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 020-supply-chain-template
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_commons/020-app-ops/020-supply-chain-template
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: dev
  dependsOn:
    - name: 030-cartographer
