---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 10p-20-kpack
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_artifacts/10-platform-ops/10p-20-kpack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: kpack-controller
    namespace: kpack
  - apiVersion: apps/v1
    kind: Deployment
    name: kpack-webhook
    namespace: kpack
