---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 10p-10-cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_artifacts/10-platform-ops/10p-10-cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: cert-manager
    namespace: cert-manager
  - apiVersion: apps/v1
    kind: Deployment
    name: cert-manager-cainjector
    namespace: cert-manager
  - apiVersion: apps/v1
    kind: Deployment
    name: cert-manager-webhook
    namespace: cert-manager
