apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    platform-layer: 10-platform-ops
    cluster: c00-dev-cluster
#
# Label for grouping
#
commonLabels:
  platform-ops: "true"

#
# Feature Toggles
#
resources:
- ../../_features/10-platform-ops/10p-00-sealed-secrets.yaml
- ../../_features/10-platform-ops/10p-10-cert-manager.yaml
- ../../_features/disable.yaml # ../../_features/10-platform-ops/10p-20-kpack.yaml
- ../../_features/10-platform-ops/10p-25-tekton.yaml
- ../../_features/10-platform-ops/10p-30-cartographer.yaml

