---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 010-dev-workload
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_commons/030-app-workload/010-dev-workload
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: dev
  dependsOn:
  - name: 000-supply-chain
