---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 30w-00-supply-chain
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_artifacts/030-app-workload/30w-00-supply-chain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: dev
  dependsOn:
  - name: 20a-20-supply-chain-template
