---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: tekton-pipeline
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://cdfoundation.github.io/tekton-helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton-pipeline
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tekton-pipeline
      sourceRef:
        kind: HelmRepository
        name: tekton-pipeline
      version: '>=0.27.0'
  interval: 1h0m0s
  releaseName: tekton-pipeline-controller
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
