---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.jenkins.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
      version: '>=3.7.0'
  interval: 1h0m0s
  releaseName: jenkins
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
