---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 020-kpack
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_commons/010-infra-ops/020-kpack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
