---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cartographer
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_commons/010-infra-ops/030-cartographer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  dependsOn:
    - name: cert-manager
