apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../c00-dev-cluster/10-platform-ops/10p-00-sealed-secrets.yaml
- ../../c00-dev-cluster/10-platform-ops/10p-10-cert-manager.yaml
- ../../c00-dev-cluster/10-platform-ops/10p-20-kpack.yaml
- ../../c00-dev-cluster/10-platform-ops/10p-30-cartographer.yaml
commonLabels:
  platform-ops: "true"
  environment: "staging"
