apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    platform-layer: 30-workload
    cluster: c00-dev-cluster
#
# Label for grouping
#
commonLabels:
  app-workload: "true"

#
# Feature Toggles
#
resources:
- ../../_features/disable.yaml # ../../_features/30-workload/30w-00-supply-chain.yaml
- ../../_features/disable.yaml # ../../_features/30-workload/30w-10-dev-workload.yaml
