---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 20a-10-kpack-builder
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_artifacts/20-app-ops/20a-10-kpack-builder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: dev
  dependsOn:
  - name: 10p-20-kpack
