apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    platform-layer: 20-app-ops
    cluster: c00-dev-cluster
#
# Label for grouping
#
commonLabels:
  app-ops: "true"

#
# Feature Toggles
#
resources:
- ../../_features/20-app-ops/20a-00-dev-ns.yaml
# - ../../_features/disable.yaml # ../../_features/20-app-ops/20a-10-kpack-builder.yaml
- ../../_features/20-app-ops/20a-15-tekton-task.yaml
- ../../_features/20-app-ops/20a-20-supply-chain-template.yaml
