---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 20a-20-supply-chain-template
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_artifacts/20-app-ops/20a-20-supply-chain-template
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: dev
  dependsOn:
  - name: 10p-30-cartographer
  - name: 20a-00-dev-ns
