---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 20a-15-tekton-task
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./_artifacts/20-app-ops/20a-15-tekton-task
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: dev
  dependsOn:
  - name: 10p-25-tekton
  - name: 20a-05-secrets
